# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 325)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formWidget.setObjectName("formWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(100, 0, 100, 0)
        self.formLayout_2.setHorizontalSpacing(50)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditPosicion = QtWidgets.QLineEdit(self.formWidget)
        self.lineEditPosicion.setObjectName("lineEditPosicion")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditPosicion)
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditTiempo = QtWidgets.QLineEdit(self.formWidget)
        self.lineEditTiempo.setObjectName("lineEditTiempo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditTiempo)
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditDireccion = QtWidgets.QLineEdit(self.formWidget)
        self.lineEditDireccion.setObjectName("lineEditDireccion")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditDireccion)
        self.verticalLayout_3.addWidget(self.formWidget)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hboxlayout.setContentsMargins(100, 0, 100, -1)
        self.hboxlayout.setSpacing(100)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonEnviar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        self.hboxlayout.addWidget(self.pushButtonEnviar)
        self.pushButtonGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGuardar.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButtonGuardar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonGuardar.setObjectName("pushButtonGuardar")
        self.hboxlayout.addWidget(self.pushButtonGuardar)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.labelVelocidad = QtWidgets.QLabel(self.centralwidget)
        self.labelVelocidad.setMinimumSize(QtCore.QSize(0, 30))
        self.labelVelocidad.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelVelocidad.setFont(font)
        self.labelVelocidad.setText("")
        self.labelVelocidad.setObjectName("labelVelocidad")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelVelocidad)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interfaz Robotica"))
        self.label.setText(_translate("MainWindow", "Posicion"))
        self.label_2.setText(_translate("MainWindow", "Tiempo"))
        self.label_3.setText(_translate("MainWindow", "Direccion"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.pushButtonGuardar.setText(_translate("MainWindow", "Guardar"))
        self.label_4.setText(_translate("MainWindow", "Velocidad: "))

